import 'package:flutter/material.dart';

import 'package:page_transition/page_transition.dart';
import 'package:styled_widget/styled_widget.dart';

import 'function_note.dart';

class PracticeNoteKit {
  openPracticeNote(
      BuildContext context, {
        required String title,
        required T button00,
        required T button01,
        required T button02,
        required T button03,
        required T button04,
        required T button05,
        required T button06,
        required T button07,
        required T button08,
        required T button09,
        required T button10,
        required T button11,
        required T button12,
        required T button13,
        required T button14,
        required T button15,
        required T button16,
        required T button17,
        required T button18,
        required T button19,
        required T button20,
        required T button21,
        required T button22,
        required T button23,
        required T button24,
        required T button25,
        required T button26,
        required T button27,
        required T button28,
        required T button29,
        required T button30,
        required T button31,
        required T button32,
        required T button33,
        required T button34,
        required T button35,
        required T button36,
        required T button37,
        required T button38,
        required T button39,
        required T button40,
        required T button41,
        required T button42,
        required T button43,
        required T button44,
        required T button45,
        required T button46,
        required T button47,
        required T button48,
        required T button49,
        required T button50,
        required T button51,
        required T button52,
        required T button53,
        required T button54,
        required T button55,
        required T button56,
        required T button57,
        required T button58,
        required T button59,
        required T button60,
        required T button61,
        required T button62,
        required T button63,
        required T button64,
        required T button65,
        required T button66,
        required T button67,
        required T button68,
        required T button69,
        required T button70,
        required T button71,
        required T button72,
        required T button73,
        required T button74,
        required T button75,
        required T button76,
        required T button77,
        required T button78,
        required T button79,
        required T button80,
        required T button81,
        required T button82,
        required T button83,
        required T button84,
        required T button85,
        required T button86,
        required T button87,
        required T button88,
        required T button89,
        required T button90,
        required T button91,
        required T button92,
        required T button93,
        required T button94,
        required T button95,
        required T button96,
        required T button97,
        required T button98,
        required T button99,
      }) {
    Navigator.push(
      context,
      PageTransition(
        type: PageTransitionType.fade,
        child: FunctionNoteKit(
          title: title,
          button00: button00,
          button01: button01,
          button02: button02,
          button03: button03,
          button04: button04,
          button05: button05,
          button06: button06,
          button07: button07,
          button08: button08,
          button09: button09,
          button10: button10,
          button11: button11,
          button12: button12,
          button13: button13,
          button14: button14,
          button15: button15,
          button16: button16,
          button17: button17,
          button18: button18,
          button19: button19,
          button20: button20,
          button21: button21,
          button22: button22,
          button23: button23,
          button24: button24,
          button25: button25,
          button26: button26,
          button27: button27,
          button28: button28,
          button29: button29,
          button30: button30,
          button31: button31,
          button32: button32,
          button33: button33,
          button34: button34,
          button35: button35,
          button36: button36,
          button37: button37,
          button38: button38,
          button39: button39,
          button40: button40,
          button41: button41,
          button42: button42,
          button43: button43,
          button44: button44,
          button45: button45,
          button46: button46,
          button47: button47,
          button48: button48,
          button49: button49,
          button50: button50,
          button51: button51,
          button52: button52,
          button53: button53,
          button54: button54,
          button55: button55,
          button56: button56,
          button57: button57,
          button58: button58,
          button59: button59,
          button60: button60,
          button61: button61,
          button62: button62,
          button63: button63,
          button64: button64,
          button65: button65,
          button66: button66,
          button67: button67,
          button68: button68,
          button69: button69,
          button70: button70,
          button71: button71,
          button72: button72,
          button73: button73,
          button74: button74,
          button75: button75,
          button76: button76,
          button77: button77,
          button78: button78,
          button79: button79,
          button80: button80,
          button81: button81,
          button82: button82,
          button83: button83,
          button84: button84,
          button85: button85,
          button86: button86,
          button87: button87,
          button88: button88,
          button89: button89,
          button90: button90,
          button91: button91,
          button92: button92,
          button93: button93,
          button94: button94,
          button95: button95,
          button96: button96,
          button97: button97,
          button98: button98,
          button99: button99,
        ),
        isIos: true,
        duration: const Duration(milliseconds: 400),
      ),
    );
  }
}
