name: june_flow_util
description: "An extremely intuitive architecture with incredibly high productivity."
version: 0.9.5
homepage: https://github.com/melodysdreamj/juneflow_util

environment:
  sdk: '>=3.2.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  styled_widget:
  page_transition:
  flutter_speed_dial:
  gap:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: